kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

