apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName:  app-pv-claim
  containers:       
    - name: mysql-container
      image: mysql:5.6
      ports:
        - containerPort: 3306
          name: mysql-port
      env:
         - name: MYSQL_ROOT_PASSWORD
           value: "MyRootPass123" 
         - name: MYSQL_DATABASE
           value: userservice       
      volumeMounts:
          - name: persistent-storage
            mountPath: /var/lib/mysql      
